name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - main  # deploy on every push to main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Set Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Deploy to GitHub Pages
        run: npx gh-pages -d dist -b gh-pages -r "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/vinit052/vite-project.git"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
